/* global module */
module.exports = {
  APP_STORE_URL: '/app',
  FOUNDING_MONTHLY_PRICE_USD: 4.99,
  FOUNDING_YEARLY_PRICE_USD: 29.99,
  LIST_MONTHLY_PRICE_USD: 29.99,
  LIST_YEARLY_PRICE_USD: 179.99,
  MONTHLY_PRICE_USD: 30,
  YEARLY_PRICE_USD: 180,
  YEARLY_MONTHLY_EQUIVALENT_USD: 15,
};
