 [functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/terms"
  to = "/terms-of-service"
  status = 301
  force = true

[[redirects]]
  from = "/privacy"
  to = "/privacy-policy"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
